package com.chrisom.sisinv.entity;
// Generated 27-oct-2015 22:28:42 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NotaRemision generated by hbm2java
 */
public class NotaRemision implements java.io.Serializable {

	private int id;
	private Vendedor vendedor;
	private Date fecha;
	private double total;
	private String nombre;
	private String direccion;
	private String ciudad;
	private Set<NotaRemisionDetalle> notaRemisionDetalles = new HashSet<NotaRemisionDetalle>(0);

	public NotaRemision() {
	}

	public NotaRemision(int id, Vendedor vendedor, Date fecha, double total) {
		this.id = id;
		this.vendedor = vendedor;
		this.fecha = fecha;
		this.total = total;
	}

	public NotaRemision(int id, Vendedor vendedor, Date fecha, double total, String nombre, String direccion,
			String ciudad, Set notaRemisionDetalles) {
		this.id = id;
		this.vendedor = vendedor;
		this.fecha = fecha;
		this.total = total;
		this.nombre = nombre;
		this.direccion = direccion;
		this.ciudad = ciudad;
		this.notaRemisionDetalles = notaRemisionDetalles;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Vendedor getVendedor() {
		return this.vendedor;
	}

	public void setVendedor(Vendedor vendedor) {
		this.vendedor = vendedor;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public double getTotal() {
		return this.total;
	}

	public void setTotal(double total) {
		this.total = total;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	public Set<NotaRemisionDetalle> getNotaRemisionDetalles() {
		return this.notaRemisionDetalles;
	}

	public void setNotaRemisionDetalles(Set<NotaRemisionDetalle> notaRemisionDetalles) {
		this.notaRemisionDetalles = notaRemisionDetalles;
	}

}
