package com.chrisom.sisinv.entity;
// Generated 09-ago-2015 19:16:00 by Hibernate Tools 3.4.0.CR1

/**
 * NotaRemisionDetalleId generated by hbm2java
 */
public class NotaRemisionDetalleId implements java.io.Serializable {

	private int cantidad;
	private double precio;
	private int notaRemisionId;
	private String productosId;

	public NotaRemisionDetalleId() {
	}

	public NotaRemisionDetalleId(int cantidad, double precio, int notaRemisionId, String productosId) {
		this.cantidad = cantidad;
		this.precio = precio;
		this.notaRemisionId = notaRemisionId;
		this.productosId = productosId;
	}

	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	public double getPrecio() {
		return this.precio;
	}

	public void setPrecio(double precio) {
		this.precio = precio;
	}

	public int getNotaRemisionId() {
		return this.notaRemisionId;
	}

	public void setNotaRemisionId(int notaRemisionId) {
		this.notaRemisionId = notaRemisionId;
	}

	public String getProductosId() {
		return this.productosId;
	}

	public void setProductosId(String productosId) {
		this.productosId = productosId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NotaRemisionDetalleId))
			return false;
		NotaRemisionDetalleId castOther = (NotaRemisionDetalleId) other;

		return (this.getCantidad() == castOther.getCantidad()) && (this.getPrecio() == castOther.getPrecio())
				&& (this.getNotaRemisionId() == castOther.getNotaRemisionId())
				&& ((this.getProductosId() == castOther.getProductosId())
						|| (this.getProductosId() != null && castOther.getProductosId() != null
								&& this.getProductosId().equals(castOther.getProductosId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCantidad();
		result = 37 * result + (int) this.getPrecio();
		result = 37 * result + this.getNotaRemisionId();
		result = 37 * result + (getProductosId() == null ? 0 : this.getProductosId().hashCode());
		return result;
	}

}
