package com.chrisom.sisinv.entity;
// Generated 27-oct-2015 22:26:03 by Hibernate Tools 3.4.0.CR1

/**
 * NotaRemisionId generated by hbm2java
 */
public class NotaRemisionId implements java.io.Serializable {

	private int id;
	private int notaRemisionDetalleId;

	public NotaRemisionId() {
	}

	public NotaRemisionId(int id, int notaRemisionDetalleId) {
		this.id = id;
		this.notaRemisionDetalleId = notaRemisionDetalleId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getNotaRemisionDetalleId() {
		return this.notaRemisionDetalleId;
	}

	public void setNotaRemisionDetalleId(int notaRemisionDetalleId) {
		this.notaRemisionDetalleId = notaRemisionDetalleId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NotaRemisionId))
			return false;
		NotaRemisionId castOther = (NotaRemisionId) other;

		return (this.getId() == castOther.getId())
				&& (this.getNotaRemisionDetalleId() == castOther.getNotaRemisionDetalleId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + this.getNotaRemisionDetalleId();
		return result;
	}

}
