package com.chrisom.sisinv.entity;
// Generated 09-ago-2015 19:16:00 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * Productos generated by hbm2java
 */
public class Producto implements java.io.Serializable {

	@Expose
	private String id;
	@Expose
	private String nombre;
	@Expose
	private double precioCompra;
	@Expose
	private int porcentaje;
	@Expose
	private Boolean iva;
	@Expose
	private Boolean habilitado;
	private Set notaRemisionDetalles = new HashSet(0);

	public Producto() {
	}

	public Producto(String id, String nombre, double precioCompra, int porcentaje) {
		this.id = id;
		this.nombre = nombre;
		this.precioCompra = precioCompra;
		this.porcentaje = porcentaje;
	}
	
	public Producto(String id, String nombre, double precioCompra, int porcentaje, Boolean iva,
			Set notaRemisionDetalles) {
		this.id = id;
		this.nombre = nombre;
		this.precioCompra = precioCompra;
		this.porcentaje = porcentaje;
		this.iva = iva;
		this.notaRemisionDetalles = notaRemisionDetalles;
	}
	
	public Producto(String id, String nombre, double precioCompra, int porcentaje, Boolean iva) {
		this.id = id;
		this.nombre = nombre;
		this.precioCompra = precioCompra;
		this.porcentaje = porcentaje;
		this.iva = iva;
	}
	
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public double getPrecioCompra() {
		return this.precioCompra;
	}

	public void setPrecioCompra(double precioCompra) {
		this.precioCompra = precioCompra;
	}

	public int getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(int porcentaje) {
		this.porcentaje = porcentaje;
	}

	public Boolean getIva() {
		return this.iva;
	}

	public void setIva(Boolean iva) {
		this.iva = iva;
	}

	public Set getNotaRemisionDetalles() {
		return this.notaRemisionDetalles;
	}

	public void setNotaRemisionDetalles(Set notaRemisionDetalles) {
		this.notaRemisionDetalles = notaRemisionDetalles;
	}
	
	public Boolean getHabilitado() {
		return habilitado;
	}

	public void setHabilitado(Boolean habilitado) {
		this.habilitado = habilitado;
	}

	@Override
	public String toString() {
		return "[id=" + id + ", nombre=" + nombre + ", precioCompra=" + precioCompra + ", porcentaje="
				+ porcentaje + ", iva=" + iva + ", habilitado=" +habilitado+"]";
	}

	
}
