package com.chrisom.sisinv.entity;
// Generated 27-oct-2015 22:28:42 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import com.google.gson.annotations.Expose;

/**
 * Vendedor generated by hbm2java
 */
public class Vendedor implements java.io.Serializable {
	@Expose
	private String id;
	@Expose
	private String nombre;
	private String direccion;
	private String telefono;
	@Expose
	private String usuario;
	private String password;
	private String email;
	private Boolean habilitado;
	private Set notaRemisions = new HashSet(0);
	private Set comisiones = new HashSet(0);

	public Vendedor() {
	}

	public Vendedor(String id, String nombre, String telefono, String usuario) {
		this.id = id;
		this.nombre = nombre;
		this.telefono = telefono;
		this.usuario = usuario;
	}

	public Vendedor(String id, String nombre, String direccion, String telefono, String usuario, String password,
			String email, Set notaRemisions) {
		this.id = id;
		this.nombre = nombre;
		this.direccion = direccion;
		this.telefono = telefono;
		this.usuario = usuario;
		this.password = password;
		this.email = email;
		this.notaRemisions = notaRemisions;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set getNotaRemisions() {
		return this.notaRemisions;
	}

	public void setNotaRemisions(Set notaRemisions) {
		this.notaRemisions = notaRemisions;
	}

	public Boolean getHabilitado() {
		return habilitado;
	}

	public void setHabilitado(Boolean habilitado) {
		this.habilitado = habilitado;
	}

	public Set getComisiones() {
		return comisiones;
	}

	public void setComisiones(Set comisiones) {
		this.comisiones = comisiones;
	}

}
